development:
  adapter: mysql2
  encoding: utf8
  database: en_donde_estoy_development
  username: root
  password: hql
  pool: 5
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: en_donde_estoy_development
  username: root
  password: 
  pool: 5
  host: localhost